
function choice = pioptions
    choice = menu('Choose a pi option','Machin''s formula',...
    'Leibniz''s formula: n-terms',...
    'Leibniz''s formula: good approximation','Exit');
while choice == 0
    disp('Invalid! Please select one of the choices')
    choice = menu('Choose a pi option','Machin''s formula',...
    'Leibniz''s formula: n-terms',...
    'Leibniz''s formula: good approximation','Exit');
end
end